version: "3.8"

services:
  app:
    image: ${APP_IMAGE:-app}
    build: .
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/db?sslmode=disable
      - PORT=8080
    ports:
      - 8080:8080

  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - 5432:5432
