version: "3.8"

services:
  app:
    image: ${APP_IMAGE:-app}
    build: .
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/db?sslmode=disable
      - GITHUB_REDIRECT_URL=http://localhost:8080/api/v1/auth/github/callback
      - GITHUB_AUTH_URL=http://localhost:8888/authorize
      - GITHUB_TOKEN_URL=http://mock-oauth:8888/access_token
      - GITHUB_USER_URL=http://mock-oauth:8888/github/user
      - GITHUB_EMAILS_URL=http://mock-oauth:8888/github/emails
      - PORT=8080
    ports:
      - 8080:8080

  mock-oauth:
    image: golang:1.16
    environment:
      - PORT=8888
    volumes:
      - .:/usr/src/app
    ports:
      - 8888:8888
    working_dir: /usr/src/app
    command: go run ./services/mock-oauth

  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - 5432:5432
